sudo: false
language: python
cache:
  - apt
  - pip
addons:
  apt:
    packages:
      - openjdk-8-jdk
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - pipenv run ./scripts/test_data/upload_test_data.sh
script:
  - pipenv run tox
after_success:
  # - pipenv run ./scripts/test_data/delete_test_data.sh
  - codecov
